```clojure
(ns spec-generator
  "Automated spec file generation from view analysis data
  
  Creates structured spec.md files following the UI Spec Template with:
  - Pre-populated sections from view analysis
  - Placeholder text for manual completion
  - Consistent formatting across all specs"
  (:require ["vscode" :as vscode]
            ["path" :as path]
            ["fs" :as fs]
            [promesa.core :as p]
            [clojure.string :as str]
            [joyride.core :as joyride]
            [view-analyzer :as va]))

(def workspace-root va/workspace-root)
(def fs-promises (.-promises fs))

(def spec-template
  "Base template for view specifications"
  "---
Title: {view-name} – UI Specification

Source:
- View: {view-path}
- Code-behind: {codebehind-path}
- ViewModel: {viewmodel-type}
- Related resources: {resources}

## 1. Purpose

{purpose-placeholder}

## 2. Visual Structure (textual outline)

**Layout Container**: {root-container}

**Major Regions**:
{regions-list}

**Key Controls**:
{controls-placeholder}

**Notable Styles/Templates**:
{styles-list}

## 3. Data & Bindings

**DataContext**: `{datacontext}`

**Bindings**:
{bindings-list}

**Converters Used**:
{converters-placeholder}

## 4. Commands & Interactions

**Commands**:
{commands-list}

**Routed Events/Behaviors**:
{events-placeholder}

**Keyboard Shortcuts**:
{keyboard-placeholder}

## 5. Navigation & Flow

**Entry Points**:
{entry-placeholder}

**Exit Points**:
{exit-placeholder}

**Dialogs/Overlays**:
{dialogs-placeholder}

## 6. States & Validation

**States**:
{states-placeholder}

**Validation Rules**:
{validation-placeholder}

## 7. Accessibility

**Focus Order**: {focus-placeholder}

**AutomationProperties**: {automation-placeholder}

**Accessibility Concerns**:
{accessibility-concerns}

## 8. Non-functional

**Performance Considerations**:
{performance-placeholder}

**Responsiveness**:
{responsiveness-placeholder}

## 9. Acceptance Criteria

{acceptance-criteria}

## Open Questions

{open-questions}

---

*Generated by spec-generator at {timestamp}*
*Analysis data available in parent analysis-report.md*
")

(defn format-bindings-list
  "Format bindings from analysis into markdown list
  
  Parameters:
  - bindings: Vector of binding maps from view-analyzer
  
  Returns: String with formatted markdown list"
  [bindings]
  (if (empty? bindings)
    "- *(No bindings detected - manual review needed)*"
    (str/join "\n"
      (map (fn [{:keys [binding-path mode line]}]
             (str "- `{Binding " binding-path "}` [" mode "] (line " line ")"))
           bindings))))

(defn format-commands-list
  "Format commands from analysis into markdown list
  
  Parameters:
  - commands: Vector of command maps from view-analyzer
  
  Returns: String with formatted markdown list"
  [commands]
  (if (empty? commands)
    "- *(No commands detected - manual review needed)*"
    (str/join "\n"
      (map (fn [{:keys [command-path line]}]
             (str "- `" command-path "` (line " line ")"))
           commands))))

(defn format-regions-list
  "Format major regions from layout analysis
  
  Parameters:
  - regions: Vector of region names
  
  Returns: String with formatted markdown list"
  [regions]
  (if (empty? regions)
    "- *(No named regions - analyze AXAML manually)*"
    (str/join "\n"
      (map (fn [region] (str "- `" region "`"))
           regions))))

(defn format-resources-list
  "Format resource dependencies
  
  Parameters:
  - resources: Map with resource types and references
  
  Returns: String with formatted list"
  [resources]
  (let [{:keys [resource-dictionaries static-resources dynamic-resources]} resources]
    (str (when (seq resource-dictionaries)
           (str "**ResourceDictionaries**:\n"
                (str/join "\n" (map #(str "- `" % "`") resource-dictionaries))
                "\n\n"))
         (when (seq dynamic-resources)
           (str "**DynamicResources** (Theme V2):\n"
                (str/join "\n" (map #(str "- `" % "`") (take 10 dynamic-resources)))
                (when (> (count dynamic-resources) 10)
                  (str "\n- *...and " (- (count dynamic-resources) 10) " more*"))
                "\n\n"))
         (when (seq static-resources)
           (str "**StaticResources**:\n"
                (str/join "\n" (map #(str "- `" % "`") (take 10 static-resources)))
                (when (> (count static-resources) 10)
                  (str "\n- *...and " (- (count static-resources) 10) " more*")))))))

(defn format-mvvm-toolkit-info
  "Format MVVM Toolkit observable properties and commands
  
  Parameters:
  - viewmodel: ViewModel analysis map
  
  Returns: String with MVVM Toolkit member documentation"
  [viewmodel]
  (if-not (:has-mvvm-toolkit? viewmodel)
    ""
    (str "\n\n### MVVM Community Toolkit Members\n\n"
         (when (seq (:observable-properties viewmodel))
           (str "**Observable Properties** (source generator):\n"
                (str/join "\n"
                  (map (fn [{:keys [field property type]}]
                         (str "- `" field "` → `" property "` : " type))
                       (:observable-properties viewmodel)))
                "\n\n"))
         (when (seq (:relay-commands viewmodel))
           (str "**Relay Commands** (source generator):\n"
                (str/join "\n"
                  (map (fn [{:keys [method command]}]
                         (str "- `" method "()` → `" command "`"))
                       (:relay-commands viewmodel))))))))

(defn generate-acceptance-criteria
  "Generate template acceptance criteria based on view analysis
  
  Parameters:
  - analysis: View analysis map
  
  Returns: String with acceptance criteria checklist"
  [analysis]
  (let [{:keys [bindings commands viewmodel]} analysis]
    (str "- [ ] View loads without errors and displays expected layout\n"
         (when (seq bindings)
           (str "- [ ] All " (count bindings) " data bindings update correctly from ViewModel\n"))
         (when (seq commands)
           (str "- [ ] All " (count commands) " commands execute as expected\n"))
         (when (:has-mvvm-toolkit? viewmodel)
           "- [ ] MVVM Toolkit generated properties and commands work correctly\n")
         "- [ ] Navigation flows to/from this view function correctly\n"
         "- [ ] Validation displays appropriate error messages\n"
         "- [ ] Accessibility: Focus order, keyboard navigation, AutomationProperties\n"
         "- [ ] Responsive layout: View scales appropriately on different resolutions\n"
         "- [ ] Theme switching: View respects light/dark theme changes\n"
         "\n*Manual review needed for completeness*")))

(defn populate-template
  "Populate spec template with view analysis data
  
  Parameters:
  - template: String with template placeholders
  - analysis: View analysis map
  
  Returns: String with populated template"
  [template analysis]
  (let [{:keys [view-name view-path viewmodel-path datacontext layout 
                bindings commands resources viewmodel analysis-timestamp]} analysis
        codebehind-path (str/replace view-path #"\.axaml$" ".axaml.cs")
        replacements {"{view-name}" view-name
                     "{view-path}" view-path
                     "{codebehind-path}" codebehind-path
                     "{viewmodel-type}" (or datacontext "*(Not specified - check code-behind)*")
                     "{resources}" (if (empty? (:resource-dictionaries resources))
                                    "*(None or inherited)*"
                                    (str/join ", " (:resource-dictionaries resources)))
                     "{purpose-placeholder}" (str "**TODO**: Describe what problem this screen solves and for whom.\n\n"
                                                 "*Hint: " view-name " provides [functionality] for [user role]*")
                     "{root-container}" (or (:root-container layout) "*(Analyze AXAML manually)*")
                     "{regions-list}" (format-regions-list (:major-regions layout))
                     "{controls-placeholder}" "**TODO**: List key controls by name and purpose"
                     "{styles-list}" (format-resources-list resources)
                     "{datacontext}" (or datacontext "*(Not specified)*")
                     "{bindings-list}" (str (format-bindings-list bindings)
                                           (format-mvvm-toolkit-info viewmodel))
                     "{converters-placeholder}" "**TODO**: Document value converters used and their purpose"
                     "{commands-list}" (format-commands-list commands)
                     "{events-placeholder}" "**TODO**: Document routed events and attached behaviors"
                     "{keyboard-placeholder}" "**TODO**: Document keyboard shortcuts and focus behavior"
                     "{entry-placeholder}" "**TODO**: How users navigate to this view (explicit + contextual)"
                     "{exit-placeholder}" "**TODO**: Where users can navigate from this view"
                     "{dialogs-placeholder}" "**TODO**: List dialogs, overlays, or transient UI elements"
                     "{states-placeholder}" "**TODO**: Loading, Empty, Error states and transitions"
                     "{validation-placeholder}" "**TODO**: Validation rules, messages, and visual cues"
                     "{focus-placeholder}" "**TODO**: Document focus order and tab navigation"
                     "{automation-placeholder}" "**TODO**: Document AutomationProperties usage"
                     "{accessibility-concerns}" (str "**TODO**: Flag any accessibility concerns:\n"
                                                    "- Missing keyboard shortcuts?\n"
                                                    "- Insufficient color contrast?\n"
                                                    "- Missing screen-reader context?")
                     "{performance-placeholder}" "**TODO**: Virtualization, heavy bindings, large datasets"
                     "{responsiveness-placeholder}" "**TODO**: Resizing behavior, responsive design"
                     "{acceptance-criteria}" (generate-acceptance-criteria analysis)
                     "{open-questions}" "**TODO**: List any uncertainties or ambiguities needing clarification"
                     "{timestamp}" (or analysis-timestamp (.toISOString (js/Date.)))}]
    (reduce (fn [text [placeholder value]]
              (str/replace text placeholder value))
            template
            replacements)))

(defn log! [message]
  (js/console.log (str "[spec-generator] " message)))

(defn create-spec-file
  "Create spec.md file for a view.

  Parameters:
  - analysis: View analysis map

  Returns: Promise resolving to created file URI"
  [analysis]
  (p/let [{:keys [view-name]} analysis
          spec-dir (.join path workspace-root "specs" "000-ui-capture" "ui" view-name)
          spec-path (.join path spec-dir "spec.md")

          ;; Ensure directory exists
          _ (.mkdir fs-promises spec-dir #js {:recursive true})

          ;; Generate and write spec content
          spec-content (populate-template spec-template analysis)
          _ (.writeFile fs-promises spec-path spec-content "utf8")]
    (log! (str "created spec → " spec-path))
    (vscode/Uri.file spec-path)))

(defn generate-specs-with-progress
  "Helper to generate a collection of specs with progress UI."
  [title analyses]
  (let [total (count analyses)]
    (cond
      (zero? total)
      (do
        (log! "no analyses provided – nothing to generate")
        (p/resolved []))

      :else
      (do
        (log! (str "starting generation for " total " views"))
        (vscode/window.withProgress
          #js {:title title
               :location (.-Notification vscode/ProgressLocation)
               :cancellable true}
          (fn [progress token]
            (let [increment (if (pos? total) (/ 100 total) 0)]
              (p/loop [remaining analyses
                       uris []]
                (cond
                  (.-isCancellationRequested token)
                  (do
                    (log! "generation cancelled")
                    (p/rejected (js/Error. "Spec generation cancelled")))

                  (empty? remaining)
                  (do
                    (log! (str "completed generation for " total " views"))
                    (p/resolved uris))

                  :else
                  (let [analysis (first remaining)
                        view-name (:view-name analysis)]
                    (.report progress #js {:message (str "Generating " view-name)
                                            :increment increment})
                    (log! (str "generating " view-name))
                    (p/let [uri (create-spec-file analysis)]
                      (p/recur (rest remaining)
                               (conj uris uri))))))))))))

(defn generate-all-specs
  "Generate spec files for all views.

  Returns: Promise resolving to vector of created file URIs"
  []
  (p/let [analyses (va/analyze-all-views)]
    (generate-specs-with-progress
      (str "Generating " (count analyses) " spec files")
      analyses)))

(defn generate-specs-for-views
  "Generate specs for specific views by name
  
  Parameters:
  - view-names: Vector of view name strings
  
  Returns: Promise resolving to vector of created file URIs"
  [view-names]
  (p/let [all-analyses (va/analyze-all-views)
    view-set (set view-names)
    filtered (filter #(contains? view-set (:view-name %)) all-analyses)]
    (generate-specs-with-progress
      (str "Generating " (count filtered) " selected specs")
      filtered)))

(defn batch-generate-specs
  "Generate specs in batches to manage memory/performance
  
  Parameters:
  - batch-size: Number of specs to generate per batch (default 10)
  
  Returns: Promise resolving to total count of generated specs"
  [batch-size]
  (p/let [effective-size (max 1 (or batch-size 10))
      analyses (va/analyze-all-views)
      batches (partition-all effective-size analyses)
          total (count analyses)]
    (log! (str "batch generation starting for " total " views (batch size " effective-size ")"))
    (vscode/window.withProgress
      #js {:title (str "Batch-generating " total " specs")
           :location (.-Notification vscode/ProgressLocation)
           :cancellable true}
      (fn [progress token]
    (let [increment (if (pos? total) (/ 100 total) 0)]
          (p/loop [remaining-batches batches
                   completed 0
                   batch-index 0]
            (cond
              (.-isCancellationRequested token)
              (do
                (log! "batch generation cancelled")
                (p/rejected (js/Error. "Spec generation cancelled")))

              (empty? remaining-batches)
              (do
                (log! (str "batch generation complete → " completed " specs"))
                (p/resolved completed))

              :else
      (let [current-batch (first remaining-batches)
                    next-count (+ completed (count current-batch))
        message (str "Batch " (inc batch-index) "/" (js/Math.ceil (/ total effective-size))
                                  " → " next-count " of " total)]
                (.report progress #js {:message message
                                       :increment (* increment (count current-batch))})
                (log! (str "running batch " (inc batch-index) " (" (count current-batch) " views)"))
                (p/let [_ (p/all (map create-spec-file current-batch))]
                  (p/recur (rest remaining-batches)
                           next-count
                           (inc batch-index))))))))))))

(defn regenerate-spec
  "Regenerate a single spec file (useful after template changes)
  
  Parameters:
  - view-name: String name of view
  
  Returns: Promise resolving to created file URI"
  [view-name]
  (p/let [pattern (str workspace-root "/Views/**/" view-name ".axaml")
          files (vscode/workspace.findFiles pattern)
          view-uri (first files)]
    (if view-uri
      (p/let [analysis (va/analyze-view view-uri)
              uri (create-spec-file analysis)]
        (vscode/window.showInformationMessage 
          (str "✓ Regenerated spec for " view-name))
        uri)
      (vscode/window.showErrorMessage (str "View not found: " view-name)))))

(comment
  ;; Usage examples (evaluate in Joyride REPL)
  
  ;; Generate all specs at once
  (generate-all-specs)
  
  ;; Generate specs in batches of 5
  (batch-generate-specs 5)
  
  ;; Generate specs for specific views
  (generate-specs-for-views ["MainWindow" "InventoryTabView" "SettingsForm"])
  
  ;; Regenerate a single spec
  (regenerate-spec "MainWindow")
  
  ;; Preview generated spec for a view
  (p/let [pattern (str workspace-root "/Views/**/MainWindow.axaml")
          files (vscode/workspace.findFiles pattern)
          view-uri (first files)
          analysis (va/analyze-view view-uri)
          spec (populate-template spec-template analysis)]
    (vscode/workspace.openTextDocument 
      (vscode/Uri.parse (str "untitled:MainWindow-spec-preview.md")))
    (p/let [doc (vscode/workspace.openTextDocument 
                  (vscode/Uri.parse (str "untitled:preview.md")))]
      (vscode/window.showTextDocument doc))))

```
